sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose run api python -m unittest discover

after_script:
  - docker-compose down
