sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose up -d api
  - sleep 20

script:
  - docker-compose ps
  - docker exec resized_api_1 python -m unittest discover

after_script:
  - docker-compose down
