apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resized
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resized
    spec:
      containers:
      - name: resized-container
        image: resized:v1
        command: ["gunicorn"]
        args: ["wsgi:app", "--bind", "0.0.0.0:5000"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/original"
          name: original
        - mountPath: "/scaled"
          name: scaled
      volumes:
        - name: original
          persistentVolumeClaim:
            claimName: myclaim-1
        - name: scaled
          persistentVolumeClaim:
            claimName: myclaim-2

---

apiVersion: v1
kind: Service
metadata:
  name: resized
  labels:
    app: resized
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: resized
